# Generated by Django 6.0.7 on 2026-08-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lunch_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lunch_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
